USE TestBase
GO 

CREATE VIEW V_TESTVIEW1 
AS 
SELECT DISTINCT CLIENT_EGN, CLIENT_SURNAME, CLIENT_NAME, CLIENT_LASTNAME, (SELECT COUNT(*)
																	FROM DATA.CREDIT CR 
																	WHERE C.CLIENT_ID = CR.CLIENT_ID AND STATUS_CODE = 'A') AS COUNT_CREDIT_A
FROM DATA.CLIENT C

SELECT * 
FROM V_TESTVIEW1